%InputVars.m
%
%Assorted input parameters for plots generated by COrVID1920
%
%variables ending in '_on' should be set to 1 or 0 for yes/no
%'_semilog' variables set to 1 have log scale for y, linear when set to 0
%'_cases_on' vaiables set to 1 will included positive test cases on plot
%'_deaths_on' variables set to 1 will include deaths on plot
%'_tests_on' variable (US only) set to 1 will plot total COVID test result 
%reports, positive plus negative
%'_hosp_on' variable (US only) set to 1 will plot hospitalized cases
%
%selected state/division/region '_plot' variables are vectors of any size
%containing the FIPS code and/or U.S. Census identifiers for a specific 
%state/division/region to be plotted, such that state_plots[09 34 36] would 
%generate a state plot for NY, NY and CT, division_plots[01 09] would 
%generate a division plot for New England and Pacific, and so on.  See 
%'state-geocodes-v2017' file to find the right numbers for corresponding 
%areas.

%US data
US_plot_on = 1;
%for U.S. data ONLY semilog_US_on = 2 will generate both linear and log
semilog_US_on = 1;
US_cases_on = 1;
US_deaths_on = 1;
US_tests_on = 1;
US_hosp_on = 1;

%Selected state data
ST_plot_on = 1;
ST_include_US = 1;
semilog_ST_on = 1;
state_plots = [09 23 25 33 44 50]

%Selected division data
DV_plot_on = 1;
DV_include_US = 1;
semilog_DV_on = 1;
div_plots = [1 9]

%Selected region data
RG_plot_on = 1;
RG_include_US = 1;
semilog_RG_on = 1;
reg_plots = [1 2 3 4]

%Custom area plots. See 'CustomAreas.m' for details & to edit inputs
CST_plot_on = 1;
CST_include_US = 1;
semilog_CST_on = 1;
run('CustomAreas.m')

%set time padding in days since 1/22/20 for start and end (x-axis) of 
%US, state/division/region, & custom plots
t_pad_us = [29 3];
t_pad_sdr = [39 3];
t_pad_cst = [29 3];

%set y limits for US, state/division/region, & custom semilog plots
y_lmt_us = [10 1000000];
y_lmt_sdr = [10 1000000];
y_lmt_cst = [10 1000000];
